Feat add fusion sync
raxjs/rax-materials pull request #3
Opened 2020-06-10 11:58 UTC by fyangstudio

Add publish config

2020-06-10 12:18 UTC, alvinhui approved these changes

2020-06-10 13:50 UTC, imsobear commented on package.json
> +    }
放外部站点上：https://fusion.design

2020-06-11 04:15 UTC, imsobear approved these changes

2020-06-16 12:20 UTC, imsobear requested changes
跟 ICE 保持一致，同步到 oss，不用走 fusion.design

2020-06-18 08:31 UTC, fyangstudio commented
> 跟 ICE 保持一致，同步到 oss，不用走 fusion.design

Done

2020-06-18 09:46 UTC, imsobear approved these changes

2020-06-18 09:46 UTC, imsobear commented on package.json
> -    "type": "rax"
这个字段还是需要的

2020-06-18 09:47 UTC, merged